FROM docker.io/library/debian:13-slim
RUN apt-get -qq update && apt-get -qq install -y --no-install-recommends python3-minimal ca-certificates && rm -rf /var/lib/apt/lists/*
COPY podmesh-managerd /usr/lib/podmesh-manager/podmesh-managerd
COPY config.json /etc/podmesh-manager/config.json
COPY entrypoint.sh /usr/local/bin/manager-universe
RUN chmod 755 /usr/lib/podmesh-manager/podmesh-managerd /usr/local/bin/manager-universe && chmod 600 /etc/podmesh-manager/config.json \
 && mkdir -p /run/podmesh-manager /var/lib/podmesh-manager && chmod 700 /run/podmesh-manager /var/lib/podmesh-manager
CMD ["/usr/local/bin/manager-universe"]
