import React,{useEffect,useState}from'react';
import {detailResources} from './explorerModel.mjs';
const value=v=>v===null||v===undefined||v===''?'Not specified':typeof v==='object'?JSON.stringify(v):String(v);
export default function Explorer({container,token,onExpired}){
 const[path,P]=useState([{id:container.Id,name:container.name}]),[data,D]=useState(null),[error,E]=useState(''),[busy,B]=useState(false),[query,Q]=useState(''),[revision,T]=useState(0);
 useEffect(()=>{const abort=new AbortController();let mounted=true;const timer=setTimeout(()=>abort.abort('Observation timed out; refresh to retry'),80000);D(null);E('');B(true);fetch(`/api/hosts/${container.host.id}/details`,{method:'POST',signal:abort.signal,headers:{'Content-Type':'application/json','X-Podmesh-Token':token},body:JSON.stringify({container_path:path.map(p=>p.id)})}).then(async r=>{if(r.status===401){if(onExpired)onExpired();throw Error('The console session was renewed; this observation reloads with it.');}const body=await r.json().catch(()=>({error:`Gateway returned HTTP ${r.status}`}));if(!r.ok||!body.ok)throw Error(body.error||'Observation unavailable');return body;}).then(r=>D(r.data)).catch(e=>{if(mounted)E(e.name==='AbortError'?'Observation timed out; refresh to retry':e.message||'Observation unavailable');}).finally(()=>{if(mounted)B(false);});return()=>{mounted=false;clearTimeout(timer);abort.abort();};},[path,container.host.id,token,revision]);
 const config=data?.configuration||{},children=Array.isArray(data?.children?.data)?data.children.data:[];
 return <section className="explorer"><h3>{data?.presentation==='shaper_universe'?'ShaperOS universe':data?.presentation==='nested_universe'?'Nested universe':'Container overview'}</h3><button className="button" disabled={busy} onClick={()=>T(revision+1)}>Refresh details</button><div className="chips" aria-label="Container path">{path.map((p,i)=><button key={p.id} onClick={()=>{P(path.slice(0,i+1));Q('');}}>{p.name}</button>)}</div>{busy&&<p role="status">Reading configuration, metrics and nested containers…</p>}{error&&<p role="alert" className="warning">{error}</p>}{data&&<><h3>{data.name} <span className="badge muted">{data.state}</span></h3><p>{data.observation_source} · Observed {new Date(data.observed_at*1000).toLocaleTimeString()} · {data.scope}</p><div className="resource-grid">{detailResources(data).map(([k,v])=><article key={k}><small>{k}</small><strong>{v}</strong></article>)}</div>{data.metrics?.status!=='observed'&&<p>{data.metrics?.reason}</p>}<p>{data.storage?.note}</p><details><summary>Configuration</summary><dl>{Object.entries(config).map(([k,v])=><React.Fragment key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{value(v)}</dd></React.Fragment>)}</dl><p>Environment variables, commands and secret mount details are not exposed.</p></details><h3>{data.presentation==='shaper_universe'?'ShaperOS bricks and child universes':'Containers inside this universe'}</h3>{data.presentation==='shaper_universe'&&<p>Parent → children · {data.classification_basis}. Logger and parent supervision remain managed by ShaperOS.</p>}{data.children?.status==='observed'?<><input aria-label="Search nested containers" placeholder="Search by name or ID" value={query} onChange={e=>Q(e.target.value)}/>{children.filter(c=>`${c.Names?.join(' ')} ${c.Id}`.toLowerCase().includes(query.toLowerCase())).map(c=><button className="nested-row" key={c.Id} disabled={path.length>=4} onClick={()=>{P([...path,{id:c.Id,name:c.Names?.[0]||c.Id.slice(0,12)}]);Q('');}}><strong>{c.Names?.[0]||c.Id.slice(0,12)} {c.shaper_brick&&<span className="badge green">{c.shaper_brick}</span>}</strong><span>{c.State} · {c.Image}</span><small>Open container →</small></button>)}{!children.length&&<p>No containers in the observed default rootful store.</p>}{path.length>=4&&<p>Maximum exploration depth reached.</p>}</>:<p className="warning">{data.children?.reason||'Nested inventory unavailable'}</p>}</>}</section>;
}
