import React,{useMemo,useState} from 'react';
import {AlertTriangle,ChevronDown,ChevronRight,GitFork,Home,Search} from 'lucide-react';
import {buildFractalModel,filterFractalModel,filterFractalOptions,fractalNodePath,projectFractalNodes} from './fractalModel.mjs';
import {formatBytes,formatCpuCores} from './hostMetricsModel.mjs';

const all=(rows,key)=>[...new Set(rows.map(row=>row[key]).filter(Boolean))].sort();
const short=id=>id?.slice(0,8)||'unknown';
const MAX_RENDERED_INVALID_RECORDS=50;
const distribution=values=>Object.entries(values).map(([name,count])=>`${name}: ${count}`).join(' · ')||'Unknown';
function Chips({label,values,value,onChange}){return <fieldset className="filter-group"><legend>{label}</legend><div className="chips"><button type="button" aria-pressed={!value} className={!value?'selected':''} onClick={()=>onChange('')}>All</button>{values.map(item=>{const option=typeof item==='string'?{value:item,label:item}:item;return <button type="button" key={option.value} aria-pressed={value===option.value} className={value===option.value?'selected':''} onClick={()=>onChange(option.value)}>{option.label}</button>})}</div></fieldset>}

export default function Fractals({containers,relationships,relationshipStatus='unavailable',relationshipError,onSelect}){
 const [filters,setFilters]=useState({fractal:'',query:'',role:'',host:'',state:''}),[fractalQuery,setFractalQuery]=useState(''),[navigation,setNavigation]=useState({});
 const universes=useMemo(()=>containers.filter(row=>row.uuid).map(row=>({uuid:row.uuid,name:row.name,hostId:row.host.id,hostName:row.host.name,state:row.State,raw:row})),[containers]);
 // Physical Podman nesting and host placement are deliberately absent from logical parentage.
 const base=useMemo(()=>buildFractalModel({universes,relationships,relationshipStatus,relationshipError}),[universes,relationships,relationshipStatus,relationshipError]);
 const model=useMemo(()=>filterFractalModel(base,filters),[base,filters]);
 const related=base.fractals.flatMap(fractal=>fractal.nodes),filterSources=[...universes,...related],invalidObserved=base.invalidObserved.slice(0,MAX_RENDERED_INVALID_RECORDS),fractalOptions=filterFractalOptions(base.fractals,fractalQuery);
 const set=(key,value)=>setFilters(current=>({...current,[key]:value}));
 const navigate=(fractalUuid,change)=>setNavigation(current=>({...current,[fractalUuid]:{focusUuid:current[fractalUuid]?.focusUuid||'',collapsedUuids:current[fractalUuid]?.collapsedUuids||[],...change}}));
 const toggle=(fractalUuid,nodeUuid)=>{const current=navigation[fractalUuid]?.collapsedUuids||[],collapsedUuids=current.includes(nodeUuid)?current.filter(uuid=>uuid!==nodeUuid):[...current,nodeUuid];navigate(fractalUuid,{collapsedUuids});};
 return <section className="fractal-view">
  {base.inputError&&<div className="relationship-state" role="alert"><AlertTriangle size={21}/><div><strong>Fractal input was not processed</strong><p>{base.inputError}</p></div></div>}
  {base.relationshipStatus==='unavailable'&&<div className="relationship-state"><AlertTriangle size={21}/><div><strong>Logical relationships unavailable</strong><p>{relationshipError||'The manager relationship API is not connected.'} Podman nesting and host placement are never used to invent parentage.</p></div></div>}
  {base.relationshipStatus==='stale'&&<div className="relationship-state" role="alert"><AlertTriangle size={21}/><div><strong>Logical relationships are stale</strong><p>{relationshipError||'The manager source is older than its configured freshness limit.'} Observed universes remain listed without inferred parentage.</p></div></div>}
  {base.relationshipStatus==='malformed'&&<div className="relationship-state" role="alert"><AlertTriangle size={21}/><div><strong>Logical relationships were rejected</strong><p>{relationshipError||'The manager response did not satisfy the bounded read-only contract.'} Observed universes remain listed without inferred parentage.</p></div></div>}
  {base.relationshipStatus==='available'&&base.issues.map(issue=><div className="relationship-state" key={issue}><AlertTriangle size={21}/><div><strong>Relationship input is partial</strong><p>{issue}</p></div></div>)}
  <div className="fractal-filters">
   <label className="search"><Search size={16}/><input aria-label="Filter by universe name or UUID" placeholder="Filter by name or UUID…" value={filters.query} onChange={event=>set('query',event.target.value)}/></label>
   <label className="search"><Search size={16}/><input aria-label="Find a fractal by name or UUID" placeholder="Find a fractal…" value={fractalQuery} onChange={event=>setFractalQuery(event.target.value)}/></label>
   <Chips label="Fractal" values={fractalOptions.map(fractal=>({value:fractal.uuid,label:`${fractal.name} · ${short(fractal.uuid)}`}))} value={filters.fractal} onChange={value=>set('fractal',value)}/>
   <Chips label="Role" values={all(filterSources,'role')} value={filters.role} onChange={value=>set('role',value)}/>
   <Chips label="Host" values={all(filterSources,'hostId')} value={filters.host} onChange={value=>set('host',value)}/>
   <Chips label="State" values={all(filterSources,'state')} value={filters.state} onChange={value=>set('state',value)}/>
  </div>
  {model.fractals.map(fractal=>{const state=navigation[fractal.uuid]||{},path=fractalNodePath(fractal.visibleNodes,state.focusUuid),focusUuid=path.length?state.focusUuid:'',visibleParents=new Set(fractal.visibleNodes.map(node=>node.parentUuid).filter(Boolean)),projected=projectFractalNodes(fractal.visibleNodes,{...state,focusUuid}),siblings=focusUuid?fractal.visibleNodes.filter(node=>node.parentUuid===path.at(-1)?.parentUuid):[];return <article className="fractal-card" key={fractal.uuid}>
   <header><div><span className="tile"><GitFork size={18}/></span><h2>{fractal.name}</h2><code>{fractal.uuid}</code></div><span className={'badge '+(fractal.stats.partial?'amber':'green')}>{fractal.stats.partial?'Partial statistics':'Complete observations'}</span></header>
   <p className="stats-scope">Statistics for {fractal.statsScope}. Context-only ancestors are excluded.</p>
   <div className="fractal-stats"><span><b>{fractal.stats.universes}</b> universes</span><span><b>{fractal.stats.metrics.contributors}/{fractal.stats.metrics.expected}</b> metric coverage</span><span><b>{formatCpuCores(fractal.stats.metrics.cpu_cores)}</b> CPU cores</span><span><b>{formatBytes(fractal.stats.metrics.memory_used_bytes)}</b> RAM use</span><span><b>{formatBytes(fractal.stats.metrics.storage_used_bytes)}</b> storage use</span><span><b>{fractal.stats.metrics.max_sample_age_seconds===null?'Unknown':`${Math.round(fractal.stats.metrics.max_sample_age_seconds)} s`}</b> oldest included sample</span><span><b>{fractal.stats.metrics.sample_window_seconds===null?'Mixed / unknown':`${fractal.stats.metrics.sample_window_seconds} s`}</b> metric window</span></div>
   <div className="fractal-distribution"><p><strong>Observed lifecycle states:</strong> {distribution(fractal.stats.states)}</p><p><strong>Observed host distribution:</strong> {distribution(fractal.stats.hosts)}</p><p>Service health is not reported by this relationship or inventory contract.</p></div>
   {fractal.issues.map(issue=><p className="fractal-issue" key={issue}>{issue}</p>)}
   <nav className="fractal-breadcrumb" aria-label={`${fractal.name} branch path`}><button type="button" aria-current={!focusUuid?'page':undefined} onClick={()=>navigate(fractal.uuid,{focusUuid:''})}><Home size={14}/>Home</button>{path.map(node=><button type="button" key={node.uuid} aria-current={node.uuid===focusUuid?'page':undefined} onClick={()=>navigate(fractal.uuid,{focusUuid:node.uuid})}>{node.name}</button>)}</nav>
   {siblings.length>1&&<div className="fractal-siblings"><small>Sibling branches</small>{siblings.map(node=><button type="button" key={node.uuid} className={node.uuid===focusUuid?'selected':''} onClick={()=>navigate(fractal.uuid,{focusUuid:node.uuid})}>{node.name}</button>)}</div>}
   <div className="fractal-tree" role="tree" aria-label={`${fractal.name} logical relationship tree`}>{projected.map(node=>{const unavailable=!node.raw,hasChildren=visibleParents.has(node.uuid),collapsed=state.collapsedUuids?.includes(node.uuid),qualifiers=[node.contextOnly&&'context only',node.cycle&&'cycle member',unavailable&&'not currently observed'].filter(Boolean).join(', ');return <div key={node.uuid} role="treeitem" aria-level={node.depth+1} aria-label={`${node.name}${qualifiers?`, ${qualifiers}`:''}`} className={['fractal-tree-row',node.contextOnly?'context-node':'',node.cycle?'cycle-node':''].filter(Boolean).join(' ')} style={{'--depth':node.depth}}><button type="button" className="tree-toggle" aria-label={`${collapsed?'Expand':'Collapse'} ${node.name}`} aria-expanded={hasChildren?!collapsed:undefined} disabled={!hasChildren} onClick={()=>toggle(fractal.uuid,node.uuid)}>{hasChildren?(collapsed?<ChevronRight size={15}/>:<ChevronDown size={15}/>):<span/>}</button><button type="button" className="tree-node" disabled={unavailable} title={unavailable?'Relationship exists, but no current host observation can be opened.':undefined} onClick={()=>node.raw&&onSelect?.(node.raw)}><GitFork size={15}/><span><strong>{node.name}</strong><small>{node.role||'Role unknown'} · {node.hostName||'Host unknown'} · {node.state||'State unknown'}</small><small className="node-qualifiers">{node.contextOnly&&'Context only · '}{node.cycle&&'Cycle member · '}{unavailable&&'Not currently observed'}</small></span><code>{short(node.uuid)}</code></button>{hasChildren&&<button type="button" className="branch-focus" onClick={()=>navigate(fractal.uuid,{focusUuid:node.uuid})}>View branch</button>}</div>})}</div>
  </article>})}
  {!!base.invalidObserved.length&&<section className="panel invalid-observed" aria-labelledby="invalid-observed-title"><div className="panel-title"><div><h2 id="invalid-observed-title">Invalid observed records</h2><p>These inventory records are visible but cannot join a logical tree until their universe UUID is corrected.</p></div><span className="badge amber">{base.invalidObserved.length}</span></div>{invalidObserved.map((node,index)=><div className="invalid-record" key={`${node.uuid}-${index}`}><span><strong>{node.name}</strong><small>{node.uuid}</small></span><span>{node.hostName||'Host unknown'}</span><span>{node.reason}</span></div>)}{base.invalidObserved.length>invalidObserved.length&&<p className="fractal-issue">Showing the first {invalidObserved.length} invalid records; {base.invalidObserved.length-invalidObserved.length} more remain in the host inventory.</p>}</section>}
  <section className="panel unassigned"><div className="panel-title"><div><h2>Unassigned observed universes</h2><p>Observed through host inventories, with no manager relationship asserted.</p></div><span className="badge muted">{model.unassigned.length} shown</span></div>{model.unassigned.map(node=><button key={node.uuid} onClick={()=>node.raw&&onSelect?.(node.raw)}><span><strong>{node.name}</strong><small>{node.uuid}</small></span><span>{node.hostName||'Host unknown'}</span><span className={'badge '+(node.state==='running'?'green':'muted')}>{node.state||'unknown'}</span></button>)}{!model.unassigned.length&&<div className="empty">No matching unassigned universes.</div>}</section>
 </section>;
}
